### ISSUE TITLE
Feature: page that explains what's verified and how to get verified

### ISSUE THREAD

**Issue by nunomaduro** [pinkary-project/pinkary.com#414]
When users click on the the verified badge, they should be redirected to a page that explains how people can become verified .

**Comment by JaiveerChavda** [comment]
This issue is already addressed, so please close it.

**Comment by MrPunyapal** [comment]
I think its partially done, clicking on badge still doesn't do anything!

**Comment by JaiveerChavda** [comment]
ok, it is currently showing small title. 
what if we redirect user to /verified page when he/she clicks on it, or may be we can show one popup model showing some information related to profile verification with a learn more link. 

<img width="1376" height="574" alt="Image" src="https://github.com/user-attachments/assets/fb30a775-90d6-4170-a5da-cc5266080873" />
